// Copies the static frontend/ site into mobile/www so Capacitor can bundle it,
// then patches www/js/config.js with the absolute URLs the native app needs
// (the web build's relative paths only work when served by frontend/nginx.conf).
//
// Usage: PRIVISEE_API_BASE_URL=https://your-backend.example.com \
//        PRIVISEE_PUBLIC_SHARE_ORIGIN=https://your-backend.example.com \
//        npm run sync-web

import { cpSync, rmSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const mobileDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const repoRoot = path.dirname(mobileDir);
const frontendDir = path.join(repoRoot, 'frontend');
const wwwDir = path.join(mobileDir, 'www');

const apiBaseUrl = process.env.PRIVISEE_API_BASE_URL || '';
const publicShareOrigin = process.env.PRIVISEE_PUBLIC_SHARE_ORIGIN || apiBaseUrl;

if (!apiBaseUrl) {
  console.warn(
    '[sync-web] PRIVISEE_API_BASE_URL is not set — the packaged app will try to ' +
    'call the backend at the local webview root and every request will fail. ' +
    'Set it to your deployed backend origin, e.g.:\n' +
    '  PRIVISEE_API_BASE_URL=https://privisee.example.com npm run sync-web'
  );
}

rmSync(wwwDir, { recursive: true, force: true });
mkdirSync(wwwDir, { recursive: true });

for (const entry of ['index.html', 'share.html', 'css', 'js', 'img']) {
  const src = path.join(frontendDir, entry);
  if (existsSync(src)) {
    cpSync(src, path.join(wwwDir, entry), { recursive: true });
  }
}

const configPath = path.join(wwwDir, 'js', 'config.js');
writeFileSync(
  configPath,
  `// Generated by mobile/scripts/sync-web.mjs from frontend/js/config.js — do not edit directly.\n` +
  `window.PRIVISEE_CONFIG = {\n` +
  `  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},\n` +
  `  publicShareOrigin: ${JSON.stringify(publicShareOrigin)},\n` +
  `};\n`
);

console.log(`[sync-web] copied frontend/ -> mobile/www (apiBaseUrl=${apiBaseUrl || '(unset)'})`);
